### ISSUE TITLE
Maven build setting problem for 0.6.0

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Letractively/aost#123]
```
Seems the jar file include a mixture of class, groovy, and java files. 
For example,


 inflated:
org/tellurium/test/helper/XMLResultReporter$_report_closure2_closure3_closure4_c
losure7.class
 inflated: org/tellurium/test/helper/XMLResultReporter.class
 inflated: org/tellurium/test/helper/XMLResultReporter.groovy
 inflated: org/tellurium/test/java/BaseTelluriumJavaTestCase.java
 inflated: org/tellurium/test/java/TelluriumJavaTestCase.java
 inflated: org/tellurium/test/java/TelluriumTestNGTestCase.java
 inflated: org/tellurium/tool/Element.java
 inflated: org/tellurium/tool/Node.java
 inflated: org/tellurium/tool/Tree.java
 inflated: org/tellurium/tool/Ui.java
 inflated: org/tellurium/tool/Uid.java
 inflated: org/tellurium/tool/UiDataReader.java
 inflated: org/tellurium/tool/UiParser.java
 inflated: org/tellurium/tool/XPath.java
 inflated: org/tellurium/tool/XPathComparator.java
 inflated: org/tellurium/tool/XPathMatcher.java
 inflated: org/tellurium/util/Helper.class
 inflated: org/tellurium/util/Helper.groovy
 inflated: org/tellurium/widget/Widget$_addSelectionByLabel_closure14.class
 inflated: org/tellurium/widget/Widget$_addSelectionByValue_closure15.class
 inflated: org/tellurium/widget/Widget$_getTableHeaderColumnNum_closure30.class
 inflated: org/tellurium/widget/Widget$_getTableMaxColumnNum_closure32.class
 inflated: org/tellurium/widget/Widget$_getTableMaxRowNum_closure31.class
 inflated: org/tellurium/widget/Widget$_getText_closure40.class
 inflated: org/tellurium/widget/Widget$_getValue_closure41.class
 inflated: org/tellurium/widget/Widget$_hasCssClass_closure47.class
 inflated: org/tellurium/widget/Widget$_isChecked_closure36.class
 inflated: org/tellurium/widget/Widget$_isDisabled_closure37.class
 inflated: org/tellurium/widget/Widget$_isEditable_closure49.class
 inflated: org/tellurium/widget/Widget$_isElementPresent_closure34.class
 inflated: org/tellurium/widget/Widget$_isSomethingSelected_closure28.class
 inflated: org/tellurium/widget/Widget$_isVisible_closure35.class
 inflated: org/tellurium/widget/Widget$_keyType_closure9.class
 inflated: org/tellurium/widget/Widget$_mouseOut_closure2.class
 inflated: org/tellurium/widget/Widget$_mouseOver_closure1.class
 inflated: org/tellurium/widget/Widget$_removeAllSelections_closure18.class
 inflated: org/tellurium/widget/Widget$_removeSelectionByLabel_closure16.class
 inflated: org/tellurium/widget/Widget$_removeSelectionByValue_closure17.class
 inflated: org/tellurium/widget/Widget$_selectByLabel_closure12.class
 inflated: org/tellurium/widget/Widget$_selectByValue_closure13.class
 inflated: org/tellurium/widget/Widget$_submit_closure48.class
 inflated: org/tellurium/widget/Widget$_type_closure8.class
 inflated: org/tellurium/widget/Widget$_typeAndReturn_closure10.class
 inflated: org/tellurium/widget/Widget$_uncheck_closure7.class
 inflated: org/tellurium/widget/Widget$_waitForElementPresent_closure38.class
 inflated: org/tellurium/widget/Widget$_waitForElementPresent_closure39.class
 inflated: org/tellurium/widget/Widget$_waitForText_closure29.class
 inflated: org/tellurium/widget/Widget.class
 inflated: org/tellurium/widget/Widget.groovy
 inflated: org/tellurium/widget/WidgetBootstrap.class
 inflated: org/tellurium/widget/WidgetBootstrap.groovy
 inflated: org/tellurium/widget/WidgetConfigurator.class
 inflated: org/tellurium/widget/WidgetConfigurator.groovy
 inflated: TelluriumConfig.groovy
  created: META-INF/maven/
  created: META-INF/maven/tellurium/
  created: META-INF/maven/tellurium/tellurium-core/
 inflated: META-INF/maven/tellurium/tellurium-core/pom.xml
 inflated: META-INF/maven/tellurium/tellurium-core/pom.properties


```

Original issue reported on code.google.com by `John.Jian.Fang@gmail.com` on 27 Feb 2009 at 6:30
